config/routes.rb
Rails.application.routes.draw do
  resources :blocks
  devise_for :users
  get "about" => "pages#about"
  get '/', to: 'blocks#index'

end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  # this runs before anything else
  before_action :set_block, only: [:show, :edit, :update, :destroy, :create]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @blocks = Block.all.order("created_at DESC")

  end

  def show
  end

  def new
    @block = Block.new
    end

  def edit
  end

  def create
    @block = Block.new(block_params)
    @block.user_id = current_user.id

      if @block.save

        render :show, notice: 'Block was successfully created.'
      else
        render :new
      end

  end

  def update
      if @block.update(block_params)
        redirect_to @block, notice: 'Block was successfully updated.'
      else
        render :edit
      end
  end

    def destroy
    @block.destroy
      redirect_to blocks_url
    end

  private

    def set_block
      if params[:id]
        @block = Block.find(params[:id])
      end
    end

    def correct_user
      @block = current_user.blocks.find_by(id: params[:id])
      if !@block
        redirect_to blocks_path, notice: "Not authorized to edit this pin" if @block.nil?
      end
    end


    # allow only white list and block black list
    def block_params
      params.require(:block).permit(:title, :description, :user_id)
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blocks/_form.html.erb
<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Editing Block</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blocks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blocks.each do |block| %> 

      <tr>
        <td><%= block.description %></td>
        <td><%= link_to 'Show', block %></td>
        <% if current_user %>
          <% if block.user_id != current_user.id %>

          <% else %>
          <td><%= link_to 'Edit', edit_block_path(block) %></td>
          <td><%= link_to 'Destroy', block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New Block', new_block_path %>
<% end %>

app/views/blocks/new.html.erb
<h1>New Block</h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @block.description %>
</p>

<% if @block.user_id == current_user %>

<%= link_to 'Edit', edit_block_path(@block) %> |
<% end %>
<%= link_to 'Back', blocks_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Igluu", root_path, class: "navbar-brand" %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Igluu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <nav class="navbar navbar-default">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>


      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", "/blocks" %></li>
          <li><%= link_to "About", "/about" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
  </nav>



  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class:"alert alert-#{name}") %>
    <% end %>
    <%= yield %>
  </div>


</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Igluu allows users to connect through their feelings and thoughts by the blocks that they post!</p>

app/views/pages/home.html.erb
<div class="jumbotron"
<h1>Welcome to Igluu!</h1>
<% if user_signed_in?%>
<h1>you have made it inside the igluu! <h1>
<%else %>
<p>
  <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>
<% end %>



</div>